test_that("no cross selection", {
  expect_equal(indirect_cross_selection_truncation(genetic.correlation = 0,
                                                   intervention.before.selection = 10,
                                                   female.fitness.cost = 0,
                                                   male.fitness.cost = 0,
                                                   female.insecticide.exposure = 1,
                                                   male.insecticide.exposure = 1,
                                                   standard.deviation = 20,
                                                   vector.length = 1000,
                                                   maximum.bioassay.survival.proportion = 1,
                                                   michaelis.menten.slope = 1,
                                                   half.population.bioassay.survival.resistance = 900,
                                                   regression.coefficient = 0.15,
                                                   regression.intercept = 0.48,
                                                   current.insecticide.efficacy = 1,
                                                   exposure.scaling.factor = 10,
                                                   heritability = 0.3), 0)
})

test_that("complete cross selection", {
  expect_equal(indirect_cross_selection_truncation(genetic.correlation = 1,
                                                   intervention.before.selection = 10,
                                                   female.fitness.cost = 0,
                                                   male.fitness.cost = 0,
                                                   female.insecticide.exposure = 1,
                                                   male.insecticide.exposure = 1,
                                                   standard.deviation = 20,
                                                   vector.length = 1000,
                                                   maximum.bioassay.survival.proportion = 1,
                                                   michaelis.menten.slope = 1,
                                                   half.population.bioassay.survival.resistance = 900,
                                                   regression.coefficient = 0.15,
                                                   regression.intercept = 0.48,
                                                   current.insecticide.efficacy = 1,
                                                   exposure.scaling.factor = 10,
                                                   heritability = 0.3), wrapper_breeders_equation_insecticide_fitness_truncation(trait.mean = 10,
                                                                                                                                 female.fitness.cost = 0,
                                                                                                                                 male.fitness.cost = 0,
                                                                                                                                 female.insecticide.exposure = 1,
                                                                                                                                 male.insecticide.exposure = 1,
                                                                                                                                 standard.deviation = 20,
                                                                                                                                 vector.length = 1000,
                                                                                                                                 maximum.bioassay.survival.proportion = 1,
                                                                                                                                 michaelis.menten.slope = 1,
                                                                                                                                 half.population.bioassay.survival.resistance = 900,
                                                                                                                                 regression.coefficient = 0.15,
                                                                                                                                 regression.intercept = 0.48,
                                                                                                                                 current.insecticide.efficacy = 1,
                                                                                                                                 exposure.scaling.factor = 10,
                                                                                                                                 heritability = 0.3))
})
