test_that("no cross selection", {
  expect_equal(wrapper_intervention_refugia_not_deployed_dispersal_truncation(insecticide.population.suppression = 0,
                                                                              intervention.before.selection = 100,
                                                                              female.fitness.cost = 0,
                                                                              male.fitness.cost = 0,
                                                                              heritability = 1,
                                                                              refugia.before.selection = 10,
                                                                              dispersal.rate = 0,
                                                                              intervention.coverage = 0.5,
                                                                              cross.selection.matrix = matrix(0, ncol = 4, nrow = 4),
                                                                              currently.deployed.insecticide = 2,
                                                                              currently.tracked.insecticide = 1,
                                                                              female.insecticide.exposure = 0.5,
                                                                              male.insecticide.exposure = 0.5,
                                                                              standard.deviation = 10,
                                                                              vector.length = 1000,
                                                                              maximum.bioassay.survival.proportion = 1,
                                                                              michaelis.menten.slope = 1,
                                                                              half.population.bioassay.survival.resistance = 900,
                                                                              regression.coefficient = 1,
                                                                              regression.intercept = 0,
                                                                              current.insecticide.efficacy = 1,
                                                                              exposure.scaling.factor = 10,
                                                                              intervention.before.selection.other = 100)[[1]], 100)
})

test_that("complete exchange", {
  expect_equal(wrapper_intervention_refugia_not_deployed_dispersal_truncation(insecticide.population.suppression = 0,
                                                                              intervention.before.selection = 100,
                                                                              female.fitness.cost = 0,
                                                                              male.fitness.cost = 0,
                                                                              heritability = 1,
                                                                              refugia.before.selection = 10,
                                                                              dispersal.rate = 1,
                                                                              intervention.coverage = 0.5,
                                                                              cross.selection.matrix = matrix(0, ncol = 4, nrow = 4),
                                                                              currently.deployed.insecticide = 2,
                                                                              currently.tracked.insecticide = 1,
                                                                              female.insecticide.exposure = 0.5,
                                                                              male.insecticide.exposure = 0.5,
                                                                              standard.deviation = 10,
                                                                              vector.length = 1000,
                                                                              maximum.bioassay.survival.proportion = 1,
                                                                              michaelis.menten.slope = 1,
                                                                              half.population.bioassay.survival.resistance = 900,
                                                                              regression.coefficient = 1,
                                                                              regression.intercept = 0,
                                                                              current.insecticide.efficacy = 1,
                                                                              exposure.scaling.factor = 10,
                                                                              intervention.before.selection.other = 10000)[[1]], 10)

  expect_equal(wrapper_intervention_refugia_not_deployed_dispersal_truncation(insecticide.population.suppression = 0,
                                                                              intervention.before.selection = 100,
                                                                              female.fitness.cost = 0,
                                                                              male.fitness.cost = 0,
                                                                              heritability = 1,
                                                                              refugia.before.selection = 10,
                                                                              dispersal.rate = 1,
                                                                              intervention.coverage = 0.5,
                                                                              cross.selection.matrix = matrix(0, ncol = 4, nrow = 4),
                                                                              currently.deployed.insecticide = 2,
                                                                              currently.tracked.insecticide = 1,
                                                                              female.insecticide.exposure = 0.5,
                                                                              male.insecticide.exposure = 0.5,
                                                                              standard.deviation = 10,
                                                                              vector.length = 1000,
                                                                              maximum.bioassay.survival.proportion = 1,
                                                                              michaelis.menten.slope = 1,
                                                                              half.population.bioassay.survival.resistance = 900,
                                                                              regression.coefficient = 1,
                                                                              regression.intercept = 0,
                                                                              current.insecticide.efficacy = 1,
                                                                              exposure.scaling.factor = 10,
                                                                              intervention.before.selection.other = 10000)[[2]], 100)
})





